apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui
  namespace: argocd

spec: 
  project: default
  source:
    repoURL: https://github.com/karthikramana25-pixel/guestbook.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-ui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
